create table if not exists public.mind_core_state (
  id text primary key,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.mind_core_cycles (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null check (status in ('running','completed','failed')),
  trigger_source text not null default 'manual',
  focus text,
  summary jsonb,
  error text
);

create table if not exists public.mind_core_evidence (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null references public.mind_core_cycles(id) on delete cascade,
  source_url text not null,
  source_kind text not null,
  source_title text,
  observed jsonb not null,
  fetched_at timestamptz not null default now()
);

alter table public.mind_core_state enable row level security;
alter table public.mind_core_cycles enable row level security;
alter table public.mind_core_evidence enable row level security;

revoke all on table public.mind_core_state from anon, authenticated;
revoke all on table public.mind_core_cycles from anon, authenticated;
revoke all on table public.mind_core_evidence from anon, authenticated;
revoke all on sequence public.mind_core_cycles_id_seq from anon, authenticated;
revoke all on sequence public.mind_core_evidence_id_seq from anon, authenticated;

create index if not exists mind_core_evidence_cycle_id_idx on public.mind_core_evidence(cycle_id);


create table if not exists public.mind_core_goals (
  id bigint generated by default as identity primary key,
  goal_key text not null unique,
  kind text not null,
  target jsonb not null default '{}'::jsonb,
  rationale text,
  priority double precision not null default 0.5 check (priority >= 0 and priority <= 1),
  status text not null default 'pending' check (status in ('pending','running','completed','failed')),
  recurrence_minutes integer,
  not_before timestamptz not null default now(),
  created_from_cycle bigint references public.mind_core_cycles(id) on delete set null,
  last_run_at timestamptz,
  run_count integer not null default 0,
  last_result jsonb,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.mind_core_goals enable row level security;
revoke all on table public.mind_core_goals from anon, authenticated;
revoke all on sequence public.mind_core_goals_id_seq from anon, authenticated;

create index if not exists mind_core_goals_sched_idx
  on public.mind_core_goals(status, not_before, priority desc);

create index if not exists mind_core_goals_created_from_cycle_idx
  on public.mind_core_goals(created_from_cycle);


create table if not exists public.mind_core_mechanisms (
  id bigint generated by default as identity primary key,
  mechanism_key text not null unique,
  ordinal integer not null unique,
  name text not null,
  kind text not null,
  description text not null,
  capabilities jsonb not null default '[]'::jsonb,
  constraints jsonb not null default '[]'::jsonb,
  status text not null check (status in ('probation','admitted','rejected','disabled')),
  evidence jsonb not null default '{}'::jsonb,
  admitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mind_core_mechanism_events (
  id bigint generated by default as identity primary key,
  mechanism_id bigint not null references public.mind_core_mechanisms(id) on delete cascade,
  cycle_id bigint references public.mind_core_cycles(id) on delete set null,
  event_type text not null,
  request jsonb,
  result jsonb,
  ok boolean not null,
  created_at timestamptz not null default now()
);

alter table public.mind_core_mechanisms enable row level security;
alter table public.mind_core_mechanism_events enable row level security;

revoke all on table public.mind_core_mechanisms from anon, authenticated;
revoke all on table public.mind_core_mechanism_events from anon, authenticated;
revoke all on sequence public.mind_core_mechanisms_id_seq from anon, authenticated;
revoke all on sequence public.mind_core_mechanism_events_id_seq from anon, authenticated;

create index if not exists mind_core_mechanism_events_mechanism_idx
  on public.mind_core_mechanism_events(mechanism_id, created_at desc);
create index if not exists mind_core_mechanism_events_cycle_idx
  on public.mind_core_mechanism_events(cycle_id);


create table if not exists public.mind_core_questions (
  id bigint generated by default as identity primary key,
  question_key text not null unique,
  question text not null,
  source_evidence_id bigint not null references public.mind_core_evidence(id) on delete cascade,
  mechanism_id bigint not null references public.mind_core_mechanisms(id) on delete restrict,
  pressure jsonb not null,
  interest_score double precision not null check (interest_score >= 0 and interest_score <= 1),
  status text not null default 'pending' check (status in ('pending','answered','rejected')),
  derived_goal_id bigint references public.mind_core_goals(id) on delete set null,
  answer_cycle_id bigint references public.mind_core_cycles(id) on delete set null,
  answer jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.mind_core_questions enable row level security;
revoke all on table public.mind_core_questions from anon, authenticated;
revoke all on sequence public.mind_core_questions_id_seq from anon, authenticated;

create index if not exists mind_core_questions_source_idx
  on public.mind_core_questions(source_evidence_id);
create index if not exists mind_core_questions_interest_idx
  on public.mind_core_questions(status, interest_score desc);
create index if not exists mind_core_questions_mechanism_idx
  on public.mind_core_questions(mechanism_id);
create index if not exists mind_core_questions_goal_idx
  on public.mind_core_questions(derived_goal_id);
create index if not exists mind_core_questions_answer_cycle_idx
  on public.mind_core_questions(answer_cycle_id);
