import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import { artifactHash, type RuleArtifact } from "../edge/genesis.ts";
import {
  createHeldoutEvaluator, type EvaluationRequest, type HeldoutCase, type HeldoutSuite,
} from "../edge/genesis_evaluator.ts";
import { SHADOW_SUITES } from "../edge/genesis_shadow_suites.ts";

// Independently authored admission policy: a report is admissible only when
// source trust is at least 0.8, age is at most 24 hours, and completeness is at
// least 0.9. Expected decisions are literal policy judgments, never generated by
// applyArtifact, the synthesis routine, or an evaluator callback.
const CASES: readonly HeldoutCase[] = [
  { id: "all-inclusive-boundaries", features: { trust: 0.8, age: 24, completeness: 0.9 }, expected: "accept" },
  { id: "fresh-complete-report", features: { trust: 0.92, age: 3, completeness: 0.98 }, expected: "accept" },
  { id: "perfect-report", features: { trust: 0.99, age: 0, completeness: 1 }, expected: "accept" },
  { id: "untrusted-only", features: { trust: 0.79, age: 1, completeness: 1 }, expected: "reject" },
  { id: "stale-only", features: { trust: 1, age: 25, completeness: 1 }, expected: "reject" },
  { id: "incomplete-only", features: { trust: 1, age: 1, completeness: 0.89 }, expected: "reject" },
  { id: "untrusted-and-stale", features: { trust: 0.7, age: 36, completeness: 1 }, expected: "reject" },
  { id: "stale-and-incomplete", features: { trust: 1, age: 48, completeness: 0.2 }, expected: "reject" },
  { id: "all-three-fail", features: { trust: 0.1, age: 99, completeness: 0.1 }, expected: "reject" },
  { id: "age-boundary-alone", features: { trust: 1, age: 24, completeness: 1 }, expected: "accept" },
];

const TRAINING = [
  { trust: 0.2, age: 80, completeness: 0.1 },
  { trust: 0.85, age: 12, completeness: 0.95 },
];

const GENERAL: RuleArtifact = {
  language: "NOVA-RULE-1",
  conditions: [
    { feature: "trust", op: ">=", threshold: 0.8 },
    { feature: "age", op: "<=", threshold: 24 },
    { feature: "completeness", op: ">=", threshold: 0.9 },
  ],
  combine: "AND", if_true: "accept", if_false: "reject",
};

const SHORTCUT: RuleArtifact = { ...GENERAL, conditions: [GENERAL.conditions[0]] };
const SUITE_ID = "report-admission-v1";

function suite(cases: readonly HeldoutCase[] = CASES, suiteId = SUITE_ID): HeldoutSuite {
  return { suiteId, cases };
}

async function request(artifact = GENERAL, suiteId = SUITE_ID): Promise<EvaluationRequest> {
  return { candidateId: "candidate-frozen-before-observation", artifact, artifactHash: await artifactHash(artifact), suiteId };
}

function clone<T>(value: T): T { return structuredClone(value); }

test("independent unseen cases admit the general conjunction, including inclusive boundaries", async () => {
  const evaluator = await createHeldoutEvaluator([suite()], TRAINING);
  const frozenRequest = await request();
  const verdict = await evaluator.evaluate(frozenRequest);
  assert.deepEqual(verdict, {
    candidateId: frozenRequest.candidateId, artifactHash: frozenRequest.artifactHash,
    suiteId: SUITE_ID, suiteHash: evaluator.manifest[0].suiteHash,
    passed: true, passedCount: 10, totalCount: 10,
  });
});

test("single-feature shortcut fails unseen stale and incomplete counterexamples", async () => {
  const evaluator = await createHeldoutEvaluator([suite()], TRAINING);
  const verdict = await evaluator.evaluate(await request(SHORTCUT));
  assert.equal(verdict.passed, false);
  assert.equal(verdict.passedCount, 7);
  assert.equal(verdict.totalCount, 10);
});

test("a single incorrect hidden decision is enough to reject admission", async () => {
  const artifact = clone(GENERAL);
  (artifact.conditions[1] as { threshold: number }).threshold = 25;
  const evaluator = await createHeldoutEvaluator([suite()], TRAINING);
  const verdict = await evaluator.evaluate(await request(artifact));
  assert.equal(verdict.passedCount, 9);
  assert.equal(verdict.passed, false);
});

test("manifest and verdict contain only the approved aggregate fields", async () => {
  const evaluator = await createHeldoutEvaluator([suite()], TRAINING);
  assert.deepEqual(Object.keys(evaluator).sort(), ["evaluate", "manifest", "trainingInputHashes"]);
  assert.deepEqual(Object.keys(evaluator.manifest[0]).sort(), ["suiteHash", "suiteId", "totalCount"]);
  const verdict = await evaluator.evaluate(await request());
  assert.deepEqual(Object.keys(verdict).sort(), [
    "artifactHash", "candidateId", "passed", "passedCount", "suiteHash", "suiteId", "totalCount",
  ]);
  const visible = JSON.stringify({ manifest: evaluator.manifest, verdict });
  for (const hidden of CASES) assert.equal(visible.includes(hidden.id), false);
  for (const name of ["trust", "age", "completeness", "conditions", "expected", "features"]) {
    assert.equal(visible.includes(`"${name}"`), false);
  }
  assert.equal(Object.isFrozen(evaluator), true);
  assert.equal(Object.isFrozen(evaluator.manifest), true);
  assert.equal(Object.isFrozen(evaluator.manifest[0]), true);
  assert.equal(Object.isFrozen(evaluator.trainingInputHashes), true);
  assert.equal(Object.isFrozen(verdict), true);
});

test("training commitments bind the complete public pool using independently calculated hashes", async () => {
  const evaluator = await createHeldoutEvaluator([suite()], TRAINING);
  const expected = TRAINING.map((row) => createHash("sha256").update(JSON.stringify({
    age: row.age, completeness: row.completeness, trust: row.trust,
  })).digest("hex")).sort();
  assert.deepEqual(evaluator.trainingInputHashes, expected);
  assert.equal(evaluator.trainingInputHashes.every((hash) => /^[a-f0-9]{64}$/.test(hash)), true);
  const reordered = TRAINING.map((row) => ({ completeness: row.completeness, age: row.age, trust: row.trust }));
  const same = await createHeldoutEvaluator([suite()], reordered);
  assert.deepEqual(same.trainingInputHashes, expected);
});

test("later training pool mutation cannot authorize a hidden row", async () => {
  const pool = clone(TRAINING);
  const pending = createHeldoutEvaluator([suite()], pool);
  pool[0].trust = 0.8;
  pool.push({ trust: 0.8, age: 24, completeness: 0.9 });
  const evaluator = await pending;
  const hiddenHash = createHash("sha256").update(JSON.stringify({ age: 24, completeness: 0.9, trust: 0.8 })).digest("hex");
  assert.equal(evaluator.trainingInputHashes.includes(hiddenHash), false);
  assert.equal(evaluator.trainingInputHashes.length, 2);
  assert.deepEqual(evaluator.trainingInputHashes, (await createHeldoutEvaluator([suite()], TRAINING)).trainingInputHashes);
});

test("manifest commits to independently calculated SHA-256 of frozen suite data", async () => {
  const evaluator = await createHeldoutEvaluator([suite()], TRAINING);
  const committed = {
    format: "NOVA-HELDOUT-1", suiteId: SUITE_ID,
    cases: CASES.map((row) => ({
      id: row.id,
      features: { age: row.features.age, completeness: row.features.completeness, trust: row.features.trust },
      expected: row.expected,
    })),
  };
  const expected = createHash("sha256").update(JSON.stringify(committed)).digest("hex");
  assert.equal(evaluator.manifest[0].suiteHash, expected);
});

test("suite hash is independent of feature insertion order and changes with labels", async () => {
  const reversed = CASES.map((row) => ({ ...row, features: Object.fromEntries(Object.entries(row.features).reverse()) }));
  const changed = clone(CASES) as HeldoutCase[];
  changed[0] = { ...changed[0], expected: "reject" };
  const a = await createHeldoutEvaluator([suite()], TRAINING);
  const b = await createHeldoutEvaluator([suite(reversed)], TRAINING);
  const c = await createHeldoutEvaluator([suite(changed)], TRAINING);
  assert.equal(a.manifest[0].suiteHash, b.manifest[0].suiteHash);
  assert.notEqual(a.manifest[0].suiteHash, c.manifest[0].suiteHash);
});

test("case data is snapshotted before asynchronous suite hashing starts", async () => {
  const editable = clone(CASES) as Array<{ id: string; features: Record<string, number>; expected: "accept" | "reject" }>;
  const input = [suite(editable)];
  const pending = createHeldoutEvaluator(input, TRAINING);
  editable[0].features.trust = -100;
  editable[0].expected = "reject";
  editable.push({ id: "late-case", features: { trust: -8 }, expected: "reject" });
  input.push(suite([{ id: "late-suite-case", features: { other: 42 }, expected: "reject" }], "late-suite"));
  const evaluator = await pending;
  assert.equal(evaluator.manifest.length, 1);
  const verdict = await evaluator.evaluate(await request());
  assert.equal(verdict.totalCount, 10);
  assert.equal(verdict.passed, true);
  const pristine = await createHeldoutEvaluator([suite()], TRAINING);
  assert.equal(evaluator.manifest[0].suiteHash, pristine.manifest[0].suiteHash);
});

test("submitted artifact and request identity are frozen before asynchronous artifact hashing", async () => {
  const evaluator = await createHeldoutEvaluator([suite()], TRAINING);
  const input = await request(clone(GENERAL));
  const originalHash = input.artifactHash;
  const pending = evaluator.evaluate(input);
  (input.artifact.conditions[0] as { threshold: number }).threshold = 2;
  (input as { candidateId: string }).candidateId = "changed-after-submission";
  const verdict = await pending;
  assert.equal(verdict.passed, true);
  assert.equal(verdict.artifactHash, originalHash);
  assert.equal(verdict.candidateId, "candidate-frozen-before-observation");
});

test("suite cannot be probed twice, including with a new candidate identity", async () => {
  const evaluator = await createHeldoutEvaluator([suite()], TRAINING);
  await evaluator.evaluate(await request(SHORTCUT));
  await assert.rejects(evaluator.evaluate(await request()), /suite is unavailable/);
});

test("concurrent submissions cannot both consume one private suite", async () => {
  const evaluator = await createHeldoutEvaluator([suite()], TRAINING);
  const input = await request();
  const outcomes = await Promise.allSettled([evaluator.evaluate(input), evaluator.evaluate(input)]);
  assert.equal(outcomes.filter((outcome) => outcome.status === "fulfilled").length, 1);
  assert.equal(outcomes.filter((outcome) => outcome.status === "rejected").length, 1);
});

test("untrusted artifact hash mismatch fails closed and consumes the suite", async () => {
  const evaluator = await createHeldoutEvaluator([suite()], TRAINING);
  const input = { ...await request(), artifactHash: "0".repeat(64) };
  await assert.rejects(evaluator.evaluate(input), /^Error: Invalid held-out evaluation request$/);
  await assert.rejects(evaluator.evaluate(await request()), /suite is unavailable/);
});

test("candidate cannot replace held-out cases or labels in the request", async () => {
  const evaluator = await createHeldoutEvaluator([suite()], TRAINING);
  const input = { ...await request(), cases: [{ features: { trust: 1 }, expected: "accept" }] };
  await assert.rejects(evaluator.evaluate(input), /Invalid held-out evaluation request/);
  await assert.rejects(evaluator.evaluate(await request()), /suite is unavailable/);
});

test("unknown suites are unavailable and do not consume known suites", async () => {
  const evaluator = await createHeldoutEvaluator([suite()], TRAINING);
  await assert.rejects(evaluator.evaluate(await request(GENERAL, "unknown")), /suite is unavailable/);
  assert.equal((await evaluator.evaluate(await request())).passed, true);
});

test("disjoint named suites can each be evaluated once", async () => {
  const evaluator = await createHeldoutEvaluator([
    suite(), suite([{ id: "separate-case", features: { trust: 0.95, age: 2, completeness: 0.96 }, expected: "accept" }], "second-suite"),
  ], TRAINING);
  assert.equal((await evaluator.evaluate(await request())).passed, true);
  assert.equal((await evaluator.evaluate(await request(GENERAL, "second-suite"))).passed, true);
});

test("empty evaluator configuration and empty suites are rejected", async () => {
  await assert.rejects(createHeldoutEvaluator([], TRAINING), /Invalid held-out evaluator configuration/);
  await assert.rejects(createHeldoutEvaluator([suite([])], TRAINING), /Invalid held-out evaluator configuration/);
});

test("duplicate suite names and case IDs are rejected", async () => {
  const other = { id: "other-id", features: { trust: 0.123 }, expected: "reject" as const };
  await assert.rejects(createHeldoutEvaluator([suite(), suite([other])], TRAINING), /Invalid held-out evaluator configuration/);
  await assert.rejects(createHeldoutEvaluator([suite([CASES[0], { ...other, id: CASES[0].id }])], TRAINING), /Invalid held-out evaluator configuration/);
  await assert.rejects(createHeldoutEvaluator([suite([CASES[0]]), suite([{ ...other, id: CASES[0].id }], "other")], TRAINING), /Invalid held-out evaluator configuration/);
});

test("duplicate numeric feature rows are rejected even with different IDs and labels", async () => {
  const duplicate = { ...CASES[0], id: "different-case", expected: "reject" as const };
  await assert.rejects(createHeldoutEvaluator([suite([CASES[0], duplicate])], TRAINING), /Invalid held-out evaluator configuration/);
});

test("train/held-out feature overlap is rejected regardless of key order", async () => {
  const training = [{ completeness: 0.9, age: 24, trust: 0.8 }];
  await assert.rejects(createHeldoutEvaluator([suite()], training), /Invalid held-out evaluator configuration/);
});

test("overlapping held-out suites cannot bypass isolation with different case IDs", async () => {
  const duplicate = { ...CASES[0], id: "another-suite-another-id", features: { completeness: 0.9, age: 24, trust: 0.8 } };
  await assert.rejects(createHeldoutEvaluator([suite(), suite([duplicate], "second-suite")], TRAINING), /Invalid held-out evaluator configuration/);
});

test("signed zero does not bypass overlap detection", async () => {
  const row = { id: "negative-zero", features: { feature: -0 }, expected: "reject" as const };
  await assert.rejects(createHeldoutEvaluator([suite([row])], [{ feature: 0 }]), /Invalid held-out evaluator configuration/);
});

for (const [name, invalid] of [
  ["NaN", Number.NaN], ["positive infinity", Infinity], ["negative infinity", -Infinity],
  ["string coercion", "1"], ["null", null],
] as const) {
  test(`invalid hidden feature ${name} is rejected without exposing private data`, async () => {
    const row = { id: "private-case-do-not-leak", features: { privateFeature: invalid }, expected: "reject" };
    await assert.rejects(createHeldoutEvaluator([suite([row as unknown as HeldoutCase])], TRAINING), /^Error: Invalid held-out evaluator configuration$/);
  });
}

test("missing, inherited, or invalid hidden labels are rejected", async () => {
  for (const row of [
    { id: "bad-label", features: { trust: 1 } },
    { id: "bad-label", features: { trust: 1 }, expected: true },
    Object.assign(Object.create({ expected: "accept" }), { id: "bad-label", features: { trust: 1 } }),
  ]) {
    await assert.rejects(createHeldoutEvaluator([suite([row as HeldoutCase])], TRAINING), /Invalid held-out evaluator configuration/);
  }
});

test("sparse arrays and accessor-backed trusted data are rejected without running accessors", async () => {
  await assert.rejects(createHeldoutEvaluator([suite(new Array(1))], TRAINING), /Invalid held-out evaluator configuration/);
  let reads = 0;
  const row = { id: "accessor-case", features: {}, expected: "reject" as const };
  Object.defineProperty(row.features, "trust", { enumerable: true, get() { reads += 1; return 1; } });
  await assert.rejects(createHeldoutEvaluator([suite([row])], TRAINING), /Invalid held-out evaluator configuration/);
  assert.equal(reads, 0);
});

for (const [name, makeInvalid] of [
  ["empty conjunction", () => ({ ...GENERAL, conditions: [] })],
  ["unsupported language", () => ({ ...GENERAL, language: "JavaScript" })],
  ["executable extension", () => ({ ...GENERAL, execute: "fetch('https://example.com')" })],
  ["wrong output branch", () => ({ ...GENERAL, if_false: "accept" })],
  ["unsupported operator", () => ({ ...GENERAL, conditions: [{ feature: "trust", op: "eval", threshold: 1 }] })],
  ["nonfinite threshold", () => ({ ...GENERAL, conditions: [{ feature: "trust", op: ">=", threshold: NaN }] })],
  ["sparse conditions", () => ({ ...GENERAL, conditions: new Array(1) })],
  ["over-budget conjunction", () => ({ ...GENERAL, conditions: [...GENERAL.conditions, { feature: "trust", op: "<=", threshold: 1 }] })],
  ["duplicate condition", () => ({ ...GENERAL, conditions: [GENERAL.conditions[0], GENERAL.conditions[0]] })],
  ["unsafe feature name", () => ({ ...GENERAL, conditions: [{ feature: "constructor", op: ">=", threshold: 1 }] })],
] as const) {
  test(`invalid artifact ${name} cannot pass an all-reject suite`, async () => {
    const evaluator = await createHeldoutEvaluator([suite([{ id: "all-reject", features: { trust: 0 }, expected: "reject" }])], TRAINING);
    const input = { ...await request(), artifact: makeInvalid() as RuleArtifact };
    await assert.rejects(evaluator.evaluate(input), /^Error: Invalid held-out evaluation request$/);
    await assert.rejects(evaluator.evaluate(await request()), /suite is unavailable/);
  });
}

test("candidate accessors are rejected without executing candidate code", async () => {
  const evaluator = await createHeldoutEvaluator([suite()], TRAINING);
  let reads = 0;
  const artifact = clone(GENERAL);
  Object.defineProperty(artifact.conditions[0], "threshold", { enumerable: true, get() { reads += 1; return 0.8; } });
  const input = { ...await request(), artifact };
  await assert.rejects(evaluator.evaluate(input), /Invalid held-out evaluation request/);
  assert.equal(reads, 0);
});

test("independent relation suites reject a shortcut and admit a fresh conjunction", async () => {
  const publicPool = [
    { consistency: 0.2, coverage: 0.2 }, { consistency: 0.8, coverage: 0.8 },
    { consistency: 0.6, coverage: 0.6 }, { consistency: 0.8, coverage: 0.4 },
    { consistency: 0.4, coverage: 0.8 },
  ];
  const evaluator = await createHeldoutEvaluator(SHADOW_SUITES, publicPool);
  const shortcut: RuleArtifact = {
    language: "NOVA-RULE-1", combine: "AND", if_true: "accept", if_false: "reject",
    conditions: [{ feature: "consistency", op: ">=", threshold: 0.5 }],
  };
  const general: RuleArtifact = { ...shortcut, conditions: [
    ...shortcut.conditions, { feature: "coverage", op: ">=", threshold: 0.5 },
  ] };
  const rejected = await evaluator.evaluate(await request(shortcut, "relation-v1"));
  assert.equal(rejected.passed, false);
  assert.equal(rejected.passedCount, 5);
  assert.equal(rejected.totalCount, 7);
  await assert.rejects(evaluator.evaluate(await request(general, "relation-v1")), /suite is unavailable/);
  const admitted = await evaluator.evaluate(await request(general, "relation-v2"));
  assert.equal(admitted.passed, true);
  assert.equal(admitted.passedCount, 11);
  assert.equal(admitted.totalCount, 11);
});
