import type { HeldoutSuite } from "./genesis_evaluator.ts";

/**
 * Independently authored oracle for the bounded relation-gate demonstration.
 * Admission policy: consistency >= 0.5 AND coverage >= 0.5; all other numeric
 * features are irrelevant. Decisions below are literal judgments from this
 * specification. They are not generated by the synthesizer or interpreter.
 *
 * These are transparent repository fixtures, not secret production benchmarks.
 * Pass them only to the trusted evaluator; never to the candidate synthesizer.
 * Their feature rows are disjoint from the entire public training pool and from
 * each other, including the separate suite reserved for the redesigned artifact.
 */
export const SHADOW_SUITES: readonly HeldoutSuite[] = [
  {
    suiteId: "relation-v1",
    cases: [
      { id: "r1-consistency-only-counterexample", features: { consistency: 0.9, coverage: 0.1 }, expected: "reject" },
      { id: "r1-coverage-only-counterexample", features: { consistency: 0.1, coverage: 0.9 }, expected: "reject" },
      { id: "r1-both-sufficient", features: { consistency: 0.75, coverage: 0.7 }, expected: "accept" },
      { id: "r1-neither-sufficient", features: { consistency: 0.3, coverage: 0.25 }, expected: "reject" },
      { id: "r1-consistency-boundary", features: { consistency: 0.5, coverage: 0.75 }, expected: "accept" },
      { id: "r1-consistency-below-boundary", features: { consistency: 0.49, coverage: 0.85 }, expected: "reject" },
      { id: "r1-coverage-below-boundary", features: { consistency: 0.85, coverage: 0.49 }, expected: "reject" },
    ],
  },
  {
    suiteId: "relation-v2",
    cases: [
      { id: "r2-both-inclusive-boundaries", features: { consistency: 0.5, coverage: 0.5 }, expected: "accept" },
      { id: "r2-consistency-just-above", features: { consistency: 0.500001, coverage: 0.9 }, expected: "accept" },
      { id: "r2-coverage-just-above", features: { consistency: 0.9, coverage: 0.500001 }, expected: "accept" },
      { id: "r2-consistency-just-below", features: { consistency: 0.499999, coverage: 0.9 }, expected: "reject" },
      { id: "r2-coverage-just-below", features: { consistency: 0.9, coverage: 0.499999 }, expected: "reject" },
      { id: "r2-both-insufficient", features: { consistency: 0.1, coverage: 0.15 }, expected: "reject" },
      { id: "r2-both-high", features: { consistency: 0.95, coverage: 0.95 }, expected: "accept" },
      { id: "r2-negative-decoy-accepted", features: { consistency: 0.77, coverage: 0.81, decoy: -10000 }, expected: "accept" },
      { id: "r2-positive-decoy-accepted", features: { consistency: 0.77, coverage: 0.81, decoy: 10000 }, expected: "accept" },
      { id: "r2-positive-decoy-rejected", features: { consistency: 0.79, coverage: 0.11, decoy: 10000 }, expected: "reject" },
      { id: "r2-negative-decoy-rejected", features: { consistency: 0.79, coverage: 0.11, decoy: -10000 }, expected: "reject" },
    ],
  },
];
